---
title: "Peer Review"
author: "Carol Shum"
date: "November 21, 2017"
output: md_document
---
```{r, echo=FALSE}
library("tidyverse")
Criteria<-c("Coding Style","Coding Strategy","Presentation of Graphs","Presentation of Tables","Achievement/Mastery/Creativity","Ease of Access")
Team1<-c("+","+","+","+","0","+")
Team2<-c("+","0","+","+","+","+")
Team4<-c("0","0","0","+","+","0")
Team5<-c("0","0","0","+","-","0")
Team6<-c("0","-","-","-","0","-")

peer.review<-data.frame(Criteria,Team1,Team2,Team4,Team5,Team6)

peer.review<-as.tibble(peer.review)
peer.review
```

#Comments for Team 1
+ Allen and Yimo's projects: 
+ Graphs: Interesting presentations but lack explanation/interpretation from some of the group members.
+ Some of the graphs could be better presented, but adequately answers the question. 
+ Good comment documentation and code structure. 

#Comments for Team 2
+ Ze's project:
+ Interesting analyses and adequate explanations. 
+ Some of the coding could have been replaced with functions rather than copy/paste multiple times.
+ Organized code structure.


#Comments for Team 4
+ Fuyu and Annie's project
+ Organized coding structure but need more comments to clarify functions used.
+ Good graphics but lack centralized location to display of all them at once. 
+ There should be some explanation/interpretation for the graphs.
+ Very interesting topic and the mining technique is beyond the basics. 


#Comments for Team 5
+ Anna's project:
+ The graphs could be more creatively presented, but adequate nonetheless.
+ Good explanations followed the graphs. 
+ The topics questions are generic. Because the text project deals with the New York Times, tying current event keywords (e.g.: Trump, Clinton, Climate, etc.) would give some interesting graphical presentations. 
+ Needs comments for documentation.


#Comments for Team 6
+ All members' projects (as there are no individual files):
+ No interpretation for the graphs; some of the graphs don't show up on the .Rmd file.
+ Data folder is empty.
+ Could use functions to run some of the codes so it would be easier to follow and condense the codes. 
+ No individual folders, so all the files are clustered under 1 file. Hard to comb through the work. 
+ Interesting topic but needs better execution. 



