---
title: "peer_review_deatley"
author: "Teresa DeAtley"
date: "November 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Team 1
##Coding Style – The coding style is well organized. There were errors when loading the packages such as tidey verse. (+)
##Coding strategy – I did not really understand the breakdown of the code (0) and did not know where to start when running the individual files. (0)
##Presentation of graphs – Plots are good and helpful visualizations, there are improvements that could be made with the sizing, and content and some of them are difficult to understand as a standalone (0).
##Presentation of tables – fairly good (0)
##Achievement, mastery, cleverness, creativity – The group did a good job of using the packages and skills we have gained in this course to complete this project (+)
##East of access for instructor, compliance with the course, ran with a few fixes – (0)

#Team 2
##Coding Style – could not get code to run, had errors on every file that I tried to run. (0)
##Coding strategy - coding could be organized slightly better, commenting is helpful when provided but was not consistent, was not able to get files to run so difficult to tell how the comments and code match to output (0)
##Presentation of graphs – wasn’t able to get graphs to run N/A
##Presentation of tables -  N/A
##Achievement, mastery, cleverness, creativity – like the general idea from looking at the paper file. Looks like a creative  idea (+)
##East of access for instructor, compliance with the course. Could not get files to run but they might run for others (0)

#Team 3
##Coding Style – well organized. Pretty good commenting, some sections seemed more explanatory then others. Code ran well except for object Book6igrams was not found. (+)
##Coding strategy – Well organized (+)
##Presentation of graphs – Nice graphs, with the exception of the epigrams not running (+)
##Presentation of tables – (+) 
##Achievement, mastery, cleverness, creativity – good use of the data (+) ##East of access for instructor, compliance with the course (+) 

#Team 4
##Coding Style – coding style was okay, sometimes a little chunky when it could be separated out and more explanation provided (0)
##Coding strategy – (0)
##Presentation of graphs – (0)
##Presentation of tables  - (0)
##Achievement, mastery, cleverness, creativity – A little disjointed with ted talks and harry potter, is there a reason why you chose more than one topic? (0)
##East of access for instructor, compliance with the course  (0)

#Team 5
##Coding Style – code ran well and was overall well organized (+)
##Coding strategy – it was difficult to tell the order in which to run all the files (0)
##Presentation of graphs – good visual representation, the display could have been cleaner (0)
##Presentation of tables - (0)
##Achievement, mastery, cleverness, creativity – (0)
##East of access for instructor, compliance with the course – Good use of the packages, and skills we have gained so far in this class. (+)


```

