---
title: "Peer Review - Text Analysis"
author: "Blain Morin"
date: "November 21, 2017"
output: html_document
---

#Team 1

| Topic | Mark |
|-------|------|
| Coding Style | + |
| Coding Strategy| + |
| Presentation: Graphs | 0 |
| Presentation: Tables | 0 |
| Achievement, Cleverness| + | 
| Ease of Access| - |

Missing instructions and description in the README file. There are a lot of files and folders in the directory. it wasn't obvious which ones to run. I thought the graphs answered the questions but could use some fine-tuning. Sometimes the facet wrapping makes them too small to see clearly. I think maybe adding legends or more description would help. Most of the code was commented well. It may be better to hide the code in the final output. Not all of the makefiles run.   

#Team 2

| Topic | Mark |
|-------|------|
| Coding Style | + |
| Coding Strategy| 0 |
| Presentation: Graphs | + |
| Presentation: Tables | + |
| Achievement, Cleverness| + | 
| Ease of Access| 0 |

The directory is well organized, but is missing instructions in the README file. The coding style and reproducibility is very good and most of the code is well commented. I thought the questions were interesting that the results were well exmplained. Some of the graphs are sophisticated. The makefile code runs.    


#Team 3

| Topic | Mark |
|-------|------|
| Coding Style | + |
| Coding Strategy| + |
| Presentation: Graphs | + |
| Presentation: Tables | + |
| Achievement, Cleverness| + | 
| Ease of Access| 0 |

The directory is well organized. I was impressed with the commenting in the code. I also thought that the questions were deep and well answered by the graphs. A lot of the graphs are sophisticated and reflect a clear offort for readability. The makefile code runs.      

#Team 5

| Topic | Mark |
|-------|------|
| Coding Style | 0 |
| Coding Strategy| 0 |
| Presentation: Graphs | + |
| Presentation: Tables | - |
| Achievement, Cleverness| 0 | 
| Ease of Access| _ |

The directory has a lot of files, but is missing instructions. The coding is well organized and divided into logical sections. Instead of displaying the r tibble style output, it may be better to use a function such as knitr to make nicer tables. Some of the graphs were very aesthetically pleasing. Th only makefile I saw (for Brian's project) runs.  

#Team 6

| Topic | Mark |
|-------|------|
| Coding Style | + |
| Coding Strategy| + |
| Presentation: Graphs | 0 |
| Presentation: Tables | + |
| Achievement, Cleverness| + | 
| Ease of Access| + |

The directory is well organized and it is clear which files to run. I like that the make file knitted all the projects together. Some of the graphs did not render in the html output. I thought the questions asked were interesting and graphs, tables, and descriptions were excellent. The code is well commented. The code runs.  